repos:
    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.1.7
      hooks:
        - id: remove-tabs

    - repo: https://github.com/psf/black
      rev: stable
      hooks:
        - id: black
          language_version: python3.7

    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.21
      hooks:
        - id: isort
          additional_dependencies: [toml]
          exclude: ^.*/?setup\.py$

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.761
      hooks:
        - id: mypy
          additional_dependencies: [sqlalchemy-stubs==0.3]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        - id: check-yaml
        - id: check-added-large-files
        - id: trailing-whitespace
        - id: end-of-file-fixer

    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.8
      hooks:
        - id: flake8

    - repo: https://github.com/PyCQA/bandit
      rev: 1.6.2
      hooks:
        - id: bandit
          args: ["--skip", "B104,B301,B403,B110", "--exclude", "tests/"]
